import 'package:kareki/src/config/kareki_config.dart';
import 'package:kareki/src/model/finding.dart';
import 'package:kareki/src/runner.dart';
import 'package:test/test.dart';

import '../support/test_workspace.dart';

void main() {
  late TestWorkspace workspace;

  setUp(() {
    workspace = TestWorkspace.create('kareki_generated_');
    workspace.writePubspec();
  });

  tearDown(() => workspace.dispose());

  test(
    'gen-l10n outputs are identified by configuration and ARB locales',
    () async {
      workspace.write('pubspec.yaml', '''
name: runner_fixture
environment:
  sdk: '>=3.10.0 <4.0.0'
flutter:
  generate: true
''');
      workspace.write('l10n.yaml', '''
arb-dir: assets/translations
output-dir: lib/generated/translations
output-localization-file: messages.dart
''');
      workspace.write('assets/translations/app_en.arb', '{"@@locale": "en"}');
      workspace.write('lib/api.dart', '''
class UsedByLocalization {}
class TrulyUnused {}
void configure({String? token}) => print(token);
''');
      workspace.write('lib/generated/translations/messages.dart', '''
import '../../api.dart';
UsedByLocalization create({String? unused}) => UsedByLocalization();
void setup() => configure(token: 'generated');
''');
      workspace.write(
        'lib/generated/translations/messages_en.dart',
        'class GeneratedEnglish {}',
      );
      workspace.write(
        'lib/generated/translations/messages_manual.dart',
        'class ManualHelper {}',
      );
      workspace.write('lib/other/messages.dart', 'class SameNameElsewhere {}');
      workspace.write('bin/main.dart', 'void main() {}');
      final result = await KarekiRunner().run(
        RunRequest(
          rootPath: workspace.path,
          config: KarekiConfig.load(workspace.path),
        ),
      );
      final messages = result.findings.map((f) => f.message);
      expect(
        messages,
        containsAll([
          contains("'TrulyUnused'"),
          contains("'ManualHelper'"),
          contains("'SameNameElsewhere'"),
        ]),
      );
      expect(messages, isNot(contains(contains("'UsedByLocalization'"))));
      expect(messages, isNot(contains(contains("'GeneratedEnglish'"))));
      expect(
        result.findings.where(
          (f) => f.ruleId == RuleId.unusedParameterOptional,
        ),
        isEmpty,
      );
      expect(
        result.findings.where(
          (f) => f.filePath.endsWith('/translations/messages.dart'),
        ),
        isEmpty,
      );
    },
  );

  for (final sample in <(String, String)>[
    ('model.drift.dart', ''),
    ('database.steps.dart', ''),
    ('schema_v1.dart', '// GENERATED BY drift_dev, DO NOT MODIFY.\n'),
    (
      'bridge.dart',
      '// This file is automatically generated, so please do not edit it.\n// @generated by `flutter_rust_bridge`@ 2.13.0.\n',
    ),
  ]) {
    test('recognizes ${sample.$1} and preserves outgoing references', () async {
      workspace.write('lib/api.dart', '''
class UsedByGenerator {}
class TrulyUnused {}
void configure({String? token}) => print(token);
''');
      workspace.write('lib/${sample.$1}', '''
${sample.$2}
import 'api.dart';
UsedByGenerator create({String? unused}) => UsedByGenerator();
void setup() => configure(token: 'generated');
''');
      workspace.write('bin/main.dart', 'void main() {}');
      final result = await KarekiRunner().run(
        RunRequest(
          rootPath: workspace.path,
          config: KarekiConfig.load(workspace.path),
        ),
      );
      expect(
        result.findings.where((f) => f.filePath.endsWith(sample.$1)),
        isEmpty,
      );
      final messages = result.findings.map((f) => f.message);
      expect(messages, contains(contains("'TrulyUnused'")));
      expect(messages, isNot(contains(contains("'UsedByGenerator'"))));
      expect(
        result.findings.where(
          (f) => f.ruleId == RuleId.unusedParameterOptional,
        ),
        isEmpty,
      );
    });
  }

  test(
    'a generic generated comment alone does not hide hand-written code',
    () async {
      workspace.write('lib/manual.dart', '''
// This file is automatically generated, so please do not edit it.
class StillReported {}
''');
      workspace.write('bin/main.dart', 'void main() {}');
      final result = await KarekiRunner().run(
        RunRequest(
          rootPath: workspace.path,
          config: KarekiConfig.load(workspace.path),
        ),
      );
      expect(
        result.findings.map((f) => f.message),
        contains(contains("'StillReported'")),
      );
    },
  );

  test('excluded code keeps the APIs it references alive', () async {
    workspace.write('lib/api.dart', '''
class KeptByGenerated {}
class TrulyUnused {}

void configure({String? token}) => print(token);
''');
    workspace.write('lib/model.g.dart', '''
import 'api.dart';

KeptByGenerated createModel() => KeptByGenerated();
void configureGeneratedModel() => configure(token: 'generated');
''');
    workspace.write('bin/main.dart', 'void main() {}\n');

    final result = await KarekiRunner().run(
      RunRequest(
        rootPath: workspace.path,
        config: KarekiConfig.load(workspace.path),
      ),
    );

    expect(
      result.findings.any(
        (finding) =>
            finding.ruleId == RuleId.unusedElement &&
            finding.message.contains("'KeptByGenerated'"),
      ),
      isFalse,
    );
    expect(
      result.findings.any(
        (finding) =>
            finding.ruleId == RuleId.unusedElement &&
            finding.message.contains("'TrulyUnused'"),
      ),
      isTrue,
    );
    expect(
      result.findings.any(
        (finding) =>
            finding.ruleId == RuleId.unusedParameterOptional &&
            finding.message.contains("'token'"),
      ),
      isFalse,
    );
    expect(
      result.findings.any(
        (finding) =>
            finding.ruleId == RuleId.unusedFile &&
            finding.filePath.endsWith('model.g.dart'),
      ),
      isFalse,
    );
  });
}
